# -*- coding: utf-8 -*-
"""otsu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/172MTBjFq4c3ZZxVhINg2BhtsUERnJDRG
"""

'''
import shutil

# Remove the directory and its contents
shutil.rmtree("/content/new_mask_otsu", ignore_errors=True)
# ignore_errors=True to avoid errors if the directory does not exist
'''

!unzip -q "/content/ACGPN_traindata.zip" -d "/content/ACGPN_traindata/"

import cv2
import os

# 경로
input_folder = '/content/ACGPN_traindata/train_color'
output_folder = '/content/new_mask_otsu_origin'
os.makedirs(output_folder, exist_ok=True)

# 이미지 처리
for filename in os.listdir(input_folder):
    if filename.lower().endswith(('.jpg', '.jpeg', '.png')):
        input_path = os.path.join(input_folder, filename)
        output_path = os.path.join(output_folder, filename)

        # 이미지 로드 & 그레이스케일 변환
        image = cv2.imread(input_path)
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        # Otsu 이진화
        _, mask = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

        # 흑백 반전 → 옷이 흰색, 배경이 검정색
        inverted_mask = cv2.bitwise_not(mask)

        # 마스크 저장
        cv2.imwrite(output_path, inverted_mask)

print("✅ Otsu + 흑백 반전 마스크 저장 완료!")

'''import shutil

# Remove the directory and its contents
shutil.rmtree("/content/new_mask_otsu_origin", ignore_errors=True)
# ignore_errors=True to avoid errors if the directory does not exist

!zip -r /content/new_mask_otsu_origin.zip /content/new_mask_otsu_origin/